import type { StoreBannerConfig } from '../types/storeBanner';

export interface BannerTemplate {
  id: string;
  name: string;
  description: string;
  iconName: string;
  configPatch: Partial<StoreBannerConfig>;
}

export const BANNER_TEMPLATES: BannerTemplate[] = [
  {
    id: 'showcase-modern',
    name: 'Modern Vitrin',
    description: 'Sol blokta başlık ve rozetler, sağda açılı şık telefon',
    iconName: 'Layout',
    configPatch: {
      textAlignment: 'left',
      textOffsetX: 56,
      textOffsetY: 0,
      textMaxWidth: 480,
      showAppIcon: true,
      showEyebrow: true,
      showStoreBadge: true,
      showRating: true,
      deviceCount: 1,
      devices: [
        {
          id: 'banner-dev-1',
          enabled: true,
          deviceType: 'iphone-17-pro-max',
          deviceColor: 'default',
          screenshotUrl: null,
          scale: 0.88,
          offsetX: 700,
          offsetY: 280,
          rotation: -10,
          perspectiveY: 0,
          shadowDepth: '3d-floating',
        },
        {
          id: 'banner-dev-2',
          enabled: false,
          deviceType: 'galaxy-s26-ultra',
          deviceColor: 'default',
          screenshotUrl: null,
          scale: 0.80,
          offsetX: 820,
          offsetY: 310,
          rotation: 8,
          perspectiveY: 0,
          shadowDepth: 'deep',
        },
      ],
    },
  },
  {
    id: 'play-store-classic',
    name: 'Play Store Klasik',
    description: 'Ortalanmış başlık, Google Play rozeti ve alttan yükselen telefon',
    iconName: 'Smartphone',
    configPatch: {
      textAlignment: 'center',
      textOffsetX: 0,
      textOffsetY: -120,
      textMaxWidth: 720,
      showAppIcon: true,
      showEyebrow: true,
      showStoreBadge: true,
      storeBadgeType: 'google-play',
      showRating: false,
      deviceCount: 1,
      devices: [
        {
          id: 'banner-dev-1',
          enabled: true,
          deviceType: 'galaxy-s26-ultra',
          deviceColor: 'default',
          screenshotUrl: null,
          scale: 0.82,
          offsetX: 512,
          offsetY: 380,
          rotation: 0,
          perspectiveY: 0,
          shadowDepth: 'deep',
        },
        {
          id: 'banner-dev-2',
          enabled: false,
          deviceType: 'iphone-17-pro-max',
          deviceColor: 'default',
          screenshotUrl: null,
          scale: 0.80,
          offsetX: 820,
          offsetY: 310,
          rotation: 8,
          perspectiveY: 0,
          shadowDepth: 'deep',
        },
      ],
    },
  },
  {
    id: 'dual-flagship',
    name: 'Çift Cihaz (iOS & Android)',
    description: 'İki telefon yan yana örtüşen açıyla vitrin sunumu',
    iconName: 'Copy',
    configPatch: {
      textAlignment: 'left',
      textOffsetX: 52,
      textOffsetY: 0,
      textMaxWidth: 440,
      showAppIcon: true,
      showEyebrow: true,
      showStoreBadge: true,
      storeBadgeType: 'both',
      showRating: true,
      deviceCount: 2,
      devices: [
        {
          id: 'banner-dev-1',
          enabled: true,
          deviceType: 'iphone-17-pro-max',
          deviceColor: 'default',
          screenshotUrl: null,
          scale: 0.82,
          offsetX: 630,
          offsetY: 270,
          rotation: -12,
          perspectiveY: 0,
          shadowDepth: '3d-floating',
        },
        {
          id: 'banner-dev-2',
          enabled: true,
          deviceType: 'galaxy-s26-ultra',
          deviceColor: 'default',
          screenshotUrl: null,
          scale: 0.84,
          offsetX: 830,
          offsetY: 280,
          rotation: 10,
          perspectiveY: 0,
          shadowDepth: 'deep',
        },
      ],
    },
  },
  {
    id: 'typography-banner',
    name: 'Tipografi & Marka',
    description: 'Cihaz olmadan sadece çarpıcı tipografi, ikon ve mağaza rozetleri',
    iconName: 'Type',
    configPatch: {
      textAlignment: 'center',
      textOffsetX: 0,
      textOffsetY: 0,
      textMaxWidth: 760,
      showAppIcon: true,
      appIconSize: 96,
      showEyebrow: true,
      showStoreBadge: true,
      storeBadgeType: 'both',
      showRating: true,
      deviceCount: 0,
    },
  },
];
